# This is a basic workflow to help you get started with Actions

name: "trigger-dynatrace-workflow"

# Controls when the workflow will run
on:
  workflow_dispatch:   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-actions-secrets
    name: Test custom action
    steps: 
      - name: Trigger Workflow
        id: triggerDtWorkflow
        uses: danielp-dt/trigger-Dynatrace-workflows-action@v1.0.0
        with: 
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          tenant: 'vzx38435'
          endpoint: 'dev.apps.dynatracelabs.com'
          workflow_id: '571dfd49-9e18-4603-843a-2681f40be9eb'
          payload: |
            {
              "input": {
                "test_msg": "hello world via github"
              },
              "params": {},
              "uniqueQualifier": ""
            }
      - name: Get response body
        run: |
          echo Output body ${{ steps.triggerDtWorkflow.outputs.response_body }}
